#!/usr/bin/env bash

set -euo pipefail

codesign --force \
    --timestamp \
    --entitlements="${PROJECT_DIR}/remember/remember-core.entitlements" \
    --sign - \
    -i io.defn.remember.remember-core \
    -o runtime \
    "${PROJECT_DIR}"/Resources/core/*/bin/remember-core

codesign --force \
    --timestamp \
    --entitlements="${PROJECT_DIR}/remember/remember-core.entitlements" \
    --sign - \
    -i org.racket-lang.racket \
    -o runtime \
    "${PROJECT_DIR}"/Resources/core/*/lib/Racket.framework/Versions/*/Racket

while read -r path; do
    codesign \
        --force \
        --timestamp \
        --entitlements="${PROJECT_DIR}/remember/remember-core.entitlements" \
        --sign - \
        -o runtime \
        "$path"
done < <(find "${PROJECT_DIR}"/Resources/core -name '*.dylib')
