#!/usr/bin/env bash

set -euo pipefail

codesign --force \
    --timestamp \
    --entitlements="${PROJECT_DIR}/remember/remember-core.entitlements" \
    --sign="$EXPANDED_CODE_SIGN_IDENTITY_NAME" \
    -i io.defn.remember.remember-core \
    -o runtime \
    "${PROJECT_DIR}/Resources/core/bin/remember-core"
