on: push
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: Bogdanp/setup-racket@v0.5
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'regular'
          version: '7.5'
      - run: raco pkg install --name remember core/
      - run: raco setup --avoid-main --tidy --check-pkg-deps --unused-pkg-deps remember
      - run: raco test core/
