on: push
name: CI
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: Bogdanp/setup-racket@v0.5
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'regular'
          version: '7.7'
      - run: sudo raco pkg install --auto --batch --name remember core/
      - run: sudo raco setup --avoid-main --tidy --check-pkg-deps --unused-pkg-deps remember
      - run: sudo raco test core/
