on: push
name: CI
jobs:
  build_core:
    runs-on: ${{ matrix.environment }}
    name: Build core (${{ matrix.platform }}) on ${{ matrix.environment }}
    strategy:
      matrix:
        environment: [macos-13, macos-14]
        include:
          - environment: macos-13
            platform: x86_64
            arch: x64
          - environment: macos-14
            platform: arm64
            arch: arm64
    steps:
      - uses: actions/checkout@master
      - uses: Bogdanp/setup-racket@v1.11
        with:
          architecture: ${{ matrix.arch }}
          distribution: 'full'
          variant: 'CS'
          version: '8.12'
          packages: http-easy-lib
      - name: Clone Noise
        run: |
          mkdir ../../sandbox
          env GIT_LFS_SKIP_SMUDGE=1 \
            git clone --depth 1 --branch racket-8.12 https://github.com/Bogdanp/Noise ../../sandbox/Noise
          raco pkg install -D --batch --auto ../../sandbox/noise/Racket/noise-serde-lib/
      - name: Install core
        run: raco pkg install -D --batch --auto --name remember core/
      - name: Build manual
        run: make cocoa/remember/res/manual/index.html
      - name: Build core
        run: make
      - name: Show your work
        run: find cocoa/remember/res
      - name: Upload manual
        uses: actions/upload-artifact@v4
        with:
          name: manual-${{ matrix.platform }}
          path: cocoa/remember/res/manual/
      - name: Upload core
        uses: actions/upload-artifact@v4
        with:
          name: core-${{ matrix.platform }}
          path: |
            cocoa/remember/res/core-${{ matrix.platform }}.zo
            cocoa/remember/res/runtime-${{ matrix.platform }}/
